### ISSUE TITLE
bug: intermittent client crash (on production only?)

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/ytsub-v3#179]
Occasionally crashes and get remix error page, which looks like some loader exception.
Reloading the page always resolve the issue.
It tends to happen after releasing new version?

```
Application Error
TypeError: Cannot read properties of undefined (reading 'type')
at https://ytsub-v3-hiro18181.vercel.app/build/_shared/chunk-BBXDWBHP.js:1:1357 
at Gf (https://ytsub-v3-hiro18181.vercel.app/build/_shared/chunk-26GVSG6Z.js:9:6560) 
at L.unstable_runWithPriority (https://ytsub-v3-hiro18181.vercel.app/build/_shared/chunk-26GVSG6Z.js:1:4026) 
at rn (https://ytsub-v3-hiro18181.vercel.app/build/_shared/chunk-26GVSG6Z.js:5:38448) 
at Xe (https://ytsub-v3-hiro18181.vercel.app/build/_shared/chunk-26GVSG6Z.js:9:6029) 
at yi (https://ytsub-v3-hiro18181.vercel.app/build/_shared/chunk-26GVSG6Z.js:7:10750) 
at https://ytsub-v3-hiro18181.vercel.app/build/_shared/chunk-26GVSG6Z.js:5:38670 
at L.unstable_runWithPriority (https://ytsub-v3-hiro18181.vercel.app/build/_shared/chunk-26GVSG6Z.js:1:4026) 
at rn (https://ytsub-v3-hiro18181.vercel.app/build/_shared/chunk-26GVSG6Z.js:5:38448) 
at Cs (https://ytsub-v3-
```

## todo

- [ ] sourcemap?
- [ ] tracing?
- [ ] error reporting

**Comment by hi-ogawa** [comment]
Well, it might actually reproducible on dev:

https://github.com/hi-ogawa/ytsub-v3/blob/c1e539004943c859da758095daba8514da64bda4/app/routes/videos/index.tsx#L96

```
react-dom.development.js:67 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Ne (http://localhost:3000/build/_shared/chunk-K35EFP62.js:456:22)
printWarning @ react-dom.development.js:67

---

index.tsx:96 Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at index.tsx:96:22
    at invokePassiveEffectCreate (react-dom.development.js:23487:20)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:9)
    at unstable_runWithPriority (scheduler.development.js:468:12)
    at runWithPriority$1 (react-dom.development.js:11276:10)
    at flushPassiveEffects (react-dom.development.js:23447:14)
    at performSyncWorkOnRoot (react-dom.development.js:22269:3)
(anonymous) @ index.tsx:96
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback2 @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
performSyncWorkOnRoot @ react-dom.development.js:22269
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
onChange @ components.js:57
update @ transition.js:123
loadPageData @ transition.js:842
await in loadPageData (async)
handleLoad @ transition.js:713
send @ transition.js:188
(anonymous) @ components.js:92
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback2 @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
performSyncWorkOnRoot @ react-dom.development.js:22269
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889

---

react-dom.development.js:20085 The above error occurred in the <VideoListComponent> component:

    at VideoListComponent (http://localhost:3000/build/_shared/chunk-TM5CE4CW.js:73:3)
    at DefaultComponent (http://localhost:3000/build/_shared/chunk-TM5CE4CW.js:65:27)
    at RemixRoute (http://localhost:3000/build/_shared/chunk-UOB6DUMX.js:2563:3)
    at Outlet (http://localhost:3000/build/_shared/chunk-UOB6DUMX.js:730:26)
    at div
    at div
    at div
    at Root (http://localhost:3000/build/root-TNZB2LXT.js:329:16)
    at QueryClientProvider2 (http://localhost:3000/build/_shared/chunk-4EMYIHXO.js:7263:22)
    at RootProviders (http://localhost:3000/build/root-TNZB2LXT.js:346:26)

```
